(ns bioinformatics.ex7c
  (:use [clojure.pprint]
        [bioinformatics.utils]))

(defn longest-repeat [s]
  (let [sss      (suffix-array s)
        lsi      (map-indexed vector (lcp last sss))
        [i l]    (->> (map-indexed vector (lcp last sss))
                      (apply max-key last))
        [_ t]    (nth sss i)]
    (apply str (take l t))
    ))


(comment
  (def w1 "CTTTAAATTTTAGCGTTAGCTGTTTCGCATGATCTAGAATATGGAAAAATCAGCCTATACCTCGTGGACAGAGAATTCACTAATTCCTGGCATATCCTACGAGGCGATGAAACCGTGAGTTGGATACGTTGAATAAAGCAGCATAGGTTGTACGACAGACCCGGGGGCACGTCCGCTCTCAACCAGCTTCATAAATGGAATCCTAACACTCCTCCATAAGGATTGATCATTATGACTATTGGTTTATTGCGACTTTTAAGCGACGCAAGCGCTCAAGAGTTAGGTCATTTAGTTCCAATTGCGCAAGATTACCCGCAATCGCCTATCAGCTTCGGGAAGAGATTCGACAAGGCTCCCCAAAACGCAAACTCATGAAGTGTCGTACGCTGGGAAACAGGATTGTTCACAGTGCTGTAGGAGAGGGCGACCTCCGAAGGCGCCGCACCGGCAAAGCCGCTGCCGCTTTACACTGGGTCCCCTGGAGCAGTGAAGAGGTGGAGGAAGAGGGGAAGAACCTAGTCCTGTGACAAGGATATGGGGTACGTAGCGACACACGTTAGCCACCGGGACCTATCTTAGCCATGTTCATCTTACACACCTGAGCGACAGACCCGGGGGCACGTCCGCTCTCAACCAGCTTCATAAATGGAATCCTAACACTCCTCCATAAGGATTGATCATTATGACTATTGGTTTACGCCTGTATGCACATTGCAATCTAGCAAGGTCGGGCTTTCGATAGTAGTTAATACCACCCCCTGAGGATGTAATCGAGTGCGTGGGCTTTCTGCTTATTCCCAGGATGTTATGTTACCGTGGGTATGATTCGACTGTCTTCTCACGGCGCGTGGTTGAAGTGTAGACCTGACTACACAGAACCCTAGGGGCCTCATGTAGGTACCTATTTCGAGGTTCTACACCTTATCCGTACCGTTTTTACAGTCTGCCTGATGTGCGATTCAGAGATGTTCACACGTCGTCGGGGGAAATGAGCTCCGTGAGTTTGAGGCCGAGTCGACAGACCCGGGGGCACGTCCGCTCTCAACCAGCTTCATAAATGGAATCCTAACACTCCTCCATAAGGATTGATCATTATGACTATTGGTTTATACGTCGCCGCTATGGACCATCGCTTTGTGGCTCGAACCTGCACCTCATTGAATTGCCAGGTGACGGGGTTCCTACATTTAAACACAGATGTGAGCGGAAGGCGTACTTCTAGGTGACACTACCCCTTATTAGAACCGCCAGCCCTAAGAGAACCGTGCCCACTGTGCGTAGT")
  (time (longest-repeat w1)))
