(ns genome.core
  (:require [clojure.math.combinatorics :as combo]))

(use 'clojure.pprint)

(defn gen-seq [w replacements]
  (reduce (fn [w [i c]]
            (assoc w i c)) w replacements))

(defn mutations [s k d]
  (let [cbs (combo/combinations (range k) d)
        sls (combo/selections s d)
        rps (->> (combo/cartesian-product cbs sls)
                 (map (fn [[indices replacements]]
                        (map vector indices replacements))))]
    (fn [w]
      (let [w (vec w)]
        (->> (map #(gen-seq w %) rps)
             (into #{}))))))

(defn freq-words-with-mismatches [text k d]
  (let [mf  (mutations #{\A\C\G\T} k d)]
    (->> (partition k 1 text)
         frequencies
         (mapcat (fn [[w v]] (->> (mf w)
                                  (map (fn [x] {x v})))))
         (apply merge-with +)
         (group-by val)
         (apply max-key key)
         val
         (map key)
         (cl-format *out* "~{~{~a~}~%~}")
         )))

;;;;;

(let [w1 "CACAGTAGGCGCCGGCACACACAGCCCCGGGCCCCGGGCCGCCCCGGGCCGGCGGCCGCCGGCGCCGGCACACCGGCACAGCCGTACCGGCACAGTAGTACCGGCCGGCCGGCACACCGGCACACCGGGTACACACCGGGGCGCACACACAGGCGGGCGCCGGGCCCCGGGCCGTACCGGGCCGCCGGCGGCCCACAGGCGCCGGCACAGTACCGGCACACACAGTAGCCCACACACAGGCGGGCGGTAGCCGGCGCACACACACACAGTAGGCGCACAGCCGCCCACACACACCGGCCGGCCGGCACAGGCGGGCGGGCGCACACACACCGGCACAGTAGTAGGCGGCCGGCGCACAGCC"
      g1 "GCACACAGAC"
      g2 "GCGCACACAC"]
  (time (freq-words-with-mismatches w1 10 2)))

(let [w1 "ACGTTGCATGTCGCATGATGCATGAGAGCT"
      g1 "ATGT"
      g2 "ATGC"
      g3 "CATG"
      g4 "GCAT"]
  (time (freq-words-with-mismatches w1 4 1)))

(let [w1 "TTTTTCAAGCAGGATGAGCAGGATGAATATCTCTCGTTCACCTGCGTTCACCTGTTTTTCAAGCAGGATGACGTTCACCTGCAGAAGCATTTTTCAAGCAGGATGATTTTTCAAATATCTCTTTTTTCAAGCAGGATGACAGAAGCACAGAAGCACGTTCACCTGCAGAAGCATTTTTCAAATATCTCTCAGAAGCATTTTTCAACGTTCACCTGCAGAAGCACGTTCACCTGGCAGGATGACGTTCACCTGATATCTCTTTTTTCAACAGAAGCAGCAGGATGAGCAGGATGACAGAAGCAATATCTCTATATCTCTCGTTCACCTGATATCTCTATATCTCTCAGAAGCATTTTTCAATTTTTCAACGTTCACCTGTTTTTCAAGCAGGATGAATATCTCTTTTTTCAATTTTTCAATTTTTCAACGTTCACCTGATATCTCTGCAGGATGAATATCTCTATATCTCTCGTTCACCTGTTTTTCAACAGAAGCAATATCTCTGCAGGATGAATATCTCTCAGAAGCAGCAGGATGATTTTTCAACAGAAGCAGCAGGATGACAGAAGCAATATCTCTTTTTTCAAATATCTCTCGTTCACCTGCAGAAGCACGTTCACCTGCAGAAGCATTTTTCAAGCAGGATGATTTTTCAAGCAGGATGATTTTTCAAGCAGGATGACAGAAGCAGCAGGATGAGCAGGATGATTTTTCAACGTTCACCTGATATCTCTATATCTCTGCAGGATGAATATCTCTATATCTCTTTTTTCAACAGAAGCAGCAGGATGACGTTCACCTGCGTTCACCTGATATCTCTCGTTCACCTGCGTTCACCTGCGTTCACCTGCAGAAGCACGTTCACCTGGCAGGATGAATATCTCTGCAGGATGACAGAAGCA"
      g1 "ATGT"
      g2 "ATGC"
      g3 "GATG"]
  (time (freq-words-with-mismatches w1 5 2)))
